#!/bin/bash

#-------------------- This script install some utilities needes to perform test on WRG --------------------

# mount RHEL 7.4 image

cd /run/media/root/OS/RHEL7.4x86_64/
mkdir /mnt/DVD
mount RHEL *.iso /mnt/DVD

# ipmitool installation
cd /mnt/DVD/Packages/
rpm -Uvh ipmitool*64*.rpm --nodeps --force

# VSS installation
cd /opt/BKCpkg/utility/ilVSS/ilvss-3.6.18.tar/ilvss-3.5.18/
echo 'y' > y.txt
echo 'y' >> y.txt

./install --rpms=/mnt/DVD < y.txt

cd /opt/ilvss/
dos2unix *
chmod +x **

# ISSDCM installation
cd /opt/BKCpkg/driver/fio-master/
chmod +x **
./configure
make
make install

# List ruler drivers and update them
cd /opt/BKCpkg/driver/PCIe*
echo 'y' > y.txt
echo 'y' >> y.txt
issdcm -drive_list >> /root/Desktop/drivelist.log

BIN=$(ls | grep *.bin)

for (( i=0;i<6;i++ )); do
  issdcm -drive_index $i -firmware_update $BIN < y.txt | tee ~/Desktop/SW-update.log
  echo '' >> ~/Desktop/SW-update.log
done

# Run FIO
sleep 10
for (( i=0;i<6;i++ )); do
  fio --bs=64k --numjobs=44 --iodepth=4 --loops=1 --direct=1 --invalidate=1 \
  --fsync_on_close=1 --randrepeat=1 --norandomma --time_based --runtime=60 \
  --filename=/dev/nvme"$i"n1 --name=read-phase --rw=randread >> ~/Desktop/nvme"$i"n1.log
done

